# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_auto_20170318_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='azure_groups',
            field=models.ManyToManyField(related_name='users', to='permissions.AzureGroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_fetched_groups',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='_is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='_is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
